apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-password: bW9uZ28tc2VjZXJ0   # this is a base64 of `mysql-db-secret`
  mongo-username: bW9uZ28tdXNlcm5hbWU=  # this is a base64 of `mysql-db-username`