apiVersion: v1
kind: Pod
metadata:
  name: youtube-app
  labels:
    app: youtube-app
spec:
  containers:
    - name: youtube-app
      image: myapp:0.0.1
      resources:
        requests:
          memory: "100Mi"
        limits:
          memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: youtube-app-service
spec:
  selector:
    app: youtube-app
  ports:
    - port: 8080
      targetPort: 8080